# Build the Shell Android application
name: Build Shell App

on:
  workflow_call:
    inputs:
      top-dir:
        required: true
        type: string

env:
  JAVA_HOME: /usr

jobs:
  build-shell:
    runs-on: self-hosted
    steps:
      - name: Build
        run: |
          cd -- "${{ inputs.top-dir }}"/packages/apps/Shell

          ./gradlew assembleRelease
